name: demo_graphql
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ferry: ^0.16.0+1
  graphql_flutter: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gql_http_link: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  ferry_generator: ^0.10.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
